### PR TITLE
Added Websocket endpoints for job processing information

### PR DESCRIPTION
**Pull request by oblodgett**

### CODE REVIEW

**Review by markquintontulloch — COMMENTED** [review]
Looks good as far as I can tell

**Review by markquintontulloch — APPROVED** [review]

**Comment by oblodgett** [comment]
Something has changed with the test containers. Not sure what is happening. It's why the IT's are failing.

**Comment by markquintontulloch** [comment]
Yeah, I ran into that yesterday.  Had to rerun the tests a few time to get them to pass on one of my PRs.  Something to do with the Quarkus update? Or would that not be related?

**Comment by oblodgett** [comment]
Ya I think it does have something to do with the quarkus update. We need to upgrade our OS from 1.2.4 to 2.1.0 and I think this problem will go away.

**Pull request merged**
