### PR TITLE
Scrum 1229 

### PR DESCRIPTION
**Pull request by kthorat-prog**

### CODE REVIEW

**Comment by oblodgett** [comment]
Did you want to combine both these PR together?

**Comment by kthorat-prog** [comment]
No, I only committed 1 file. Don't know why 2 PRs got combined.

**Comment by oblodgett** [comment]
This PR is showing both files.

**Comment by oblodgett** [comment]
It looks like the `SCRUM-1229` branch was taken from `EvideneCode_withMultiSelectFilter` and not taken from `alpha`?

**Comment by kthorat-prog** [comment]
I will change it now.

**Comment by kthorat-prog** [comment]
2 PRS got combined so closing this.

**Pull request closed without merging**
