### PR TITLE
Reverted tabs to spaces

### PR DESCRIPTION
**Pull request by oblodgett**
@cmpich your IDE is committing with tabs. I would be more than happy to switch this repo over to using tabs vs spaces, everyone else is using tabs.

### CODE REVIEW

**Review by cmpich — APPROVED** [review]
That is good. For Java code my IDE is using spaces instead of tabs. Looks like this needs to be configured for javascript files too.

**Comment by oblodgett** [comment]
Can we just switch your ENV to using spaces and let everyone else use tabs? as in that is what everyone is already doing?

**Comment by cmpich** [comment]
I am used to always use 4 spaces per tab to make it always look the same.

**Comment by oblodgett** [comment]
Right... and when using tabs everyone can choose whatever tabstop they want (personally I like 3) for themselves and in your case we create a gitattrbutes that changes all tabs to 4 spaces on checkout and all 4 spaces back to tabs on checkin.

**Pull request closed without merging**
