### PR TITLE
Evidence code filter changed to MultiSelect dropdown

### PR DESCRIPTION
**Pull request by kthorat-prog**

### CODE REVIEW

**Review by oblodgett — COMMENTED** [review]
Do we not want the curators to search by name or curie?

**Comment by oblodgett** [comment]
> Do we not want the curators to search by name or curie?

Oh never mind I see we are changing it to: FilterMultiSelectComponentTemplate

**Comment by kthorat-prog** [comment]
I think search only by abrevation if we want the multiselect dropdown here.

**Comment by oblodgett** [comment]
I haven't seen the ticket but this is going to imply that they can only search via abbreviation in the pull down... and when they see TAS they won't know which one to choose?

**Comment by kthorat-prog** [comment]
Ohh yes, We can wait on this one then until Chris is back.

**Comment by oblodgett** [comment]
@kthorat-prog what is happening with this PR?

**Comment by kthorat-prog** [comment]
Need to think on all options and the best way to implement this. So, closing this PR for now.

**Pull request closed without merging**
