### PR TITLE
Added release notes for 0.11.0

### PR DESCRIPTION
**Pull request by oblodgett**

### CODE REVIEW

**Review by mluypaert — CHANGES_REQUESTED** [review]
You should do some cleanup and summarizing on those release notes, those are supposed to be the easy readable summary of the most important changes made, not the autogenerated list from github.

**Review by markquintontulloch — COMMENTED** [review]
Is this meant to go into alpha?

**Comment by oblodgett** [comment]
We take this data, and copy it into confluence, it's in the GitHub release notes. It seems redundant to have to reiterate it here again, in the release notes.

**Comment by mluypaert** [comment]
> Is this meant to go into alpha?

@markquintontulloch You're right, normally this release notes update shoud have been made in the `release/v0.11.0` branch (before merging into production), and before creating the `v0.11.0` tag and github release. However, as this already happened, merging this in alpha will do (no need to the tagging and release creation over the release notes).

**Comment by mluypaert** [comment]
> We take this data, and copy it into confluence, it's in the GitHub release notes. It seems redundant to have to reiterate it here again, in the release notes.

Confluence lists sprint results, not curation software release (even though they often align on the major lines). Sprint points etc. are for example not relevant for the release notes. Github's autogenerated release notes are spread accross different pages for each release, and thus not easily browsable. They're also not easily readable, as they often contain a whole lot of PR references for any single JIRA ticket, and one feature is often implemented in multiple different JIRA tickets (UI vs API vs ...). The RELEASE-NOTES.md file is intended as an easily readable document for curators and DQMs using the curation software, to be able to tell what changed in a quick glance, and provide easy tracability accross releases. This file could also eventually be used to serve a "what's new" section in the curation UI, to easily inform users about the latest changes.

**Review by mluypaert — APPROVED** [review]
I've cleaned up the RELEASE-NOTES file in commit b9fafaa now.

**Pull request merged**
