### PR TITLE
SCRUM-245: add spock testing and compatible mocking frameworks

### PR DESCRIPTION
**Pull request by abecerra**
Ticket:
https://agr-jira.atlassian.net/browse/SCRUM-245

Evidence of integration tests running:

Screenshot_20210907_152503

With class:
Screenshot_20210907_152604

And test (not an integration, but just for running something):
Screenshot_20210907_152605

Class and Test only added to my local, not in pull request.

### CODE REVIEW

**Comment by abecerra** [comment]
> @abecerra so typically tests go in the `src/test/java` directory and have some default package lets say `org.alliancegenome.curation_api.testing` do you think you could give an example of how the mocking could work... plus it wasn't clear how the tests are being run?

- the tests go in 'src/test/groovy'
- the execution of the tests is done when building the project

**Comment by oblodgett** [comment]
"the execution of the tests is done when building the project" thats the issue. The integration tests cannot be run while building the project, only unit tests, unless we are going to setup a mock infrastructure @cmpich? Integration tests need to be run separately via a `mvn verify` or some other command... see the linked article.

**Comment by abecerra** [comment]
> need



> "the execution of the tests is done when building the project" thats the issue. The integration tests cannot be run while building the project, only unit tests, unless we are going to setup a mock infrastructure @cmpich? Integration tests need to be run separately via a `mvn verify` or some other command... see the linked article.

Related findings in the comment:
https://agr-jira.atlassian.net/browse/SCRUM-245?focusedCommentId=31473

**Comment by abecerra** [comment]
Closing because spock framework is not integrated to Quarkus yet.

**Pull request closed without merging**
