### PR TITLE
Input field character search changed from 10 to 20 (ngrams & tokenizers)

### PR DESCRIPTION
**Pull request by kthorat-prog**
Input field character search changed from 10 to 20 (ngrams & tokenizers)

### CODE REVIEW

**Comment by oblodgett** [comment]
@kthorat-prog this is a full reindex?

**Review by oblodgett — APPROVED** [review]

**Comment by kthorat-prog** [comment]
yes....I am afraid so.... :(

**Comment by kthorat-prog** [comment]
@oblodgett Verify-test-api is failing. Do you have an idea why?

**Comment by oblodgett** [comment]
@kthorat-prog I don't know I will just kicked them off again

**Pull request merged**
