### PR TITLE
SCRUM-3290 (update) Fix 'failed to lazily initialize a collection' error

### PR DESCRIPTION
**Pull request by markquintontulloch**

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]

**Comment by markquintontulloch** [comment]
@adamgibs @oblodgett Any idea why the UI tests are failing here.  I can't make much sense of the logs!

**Comment by markquintontulloch** [comment]
UI tests are passing locally

**Comment by adamgibs** [comment]
@markquintontulloch That's really, odd. I've just started them again, but they shouldn't be failing since the only changes were on the backend.

**Comment by markquintontulloch** [comment]
Hmm, I ran `make all` in src/main/cliapp, followed by `npm test` and now I get:
 ```
FAIL  src/containers/conditionRelationPage/__tests__/ConditionRelationTable.test.js
  ● Test suite failed to run

    Cannot find module '@testing-library/dom/dist/helpers.js' from 'node_modules/@testing-library/user-event/dist/cjs/utils/misc/getWindow.js'

    Require stack:
      node_modules/@testing-library/user-event/dist/cjs/utils/misc/getWindow.js
      node_modules/@testing-library/user-event/dist/cjs/utils/dataTransfer/Clipboard.js
      node_modules/@testing-library/user-event/dist/cjs/event/behavior/click.js
      node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js
      node_modules/@testing-library/user-event/dist/cjs/document/prepareDocument.js
      node_modules/@testing-library/user-event/dist/cjs/setup/setup.js
      node_modules/@testing-library/user-event/dist/cjs/setup/index.js
      node_modules/@testing-library/user-event/dist/cjs/index.js
      src/containers/conditionRelationPage/__tests__/ConditionRelationTable.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/@testing-library/user-event/dist/cjs/utils/misc/getWindow.js:5:18)

Test Suites: 1 failed, 16 passed, 17 total`
```

**Comment by oblodgett** [comment]
@markquintontulloch @adamgibs do these tests fail locally?

**Comment by oblodgett** [comment]
So ya these fail for me locally...
`cd agr_curation/src/main/cliapp`
`rm -fr node_modules`
`rm  package-lock.json`
`npm install --legacy-peer-deps`
`npm test -- --watchAll=false` -> FAIL
I would guess this is a package issue... and not our tests issue. I was surprised to see all this output I don't recall seeing all this before?

**Comment by markquintontulloch** [comment]
@oblodgett They are passing for Adam and myself locally after adding `"@testing-library/dom": "^9.3.1"` to src/main/cliapp/package.json

EDIT:  Forget that!  I hadn't deleted node_modules before.  Seeing all the same errors as in Github now.

**Pull request merged**
