### PR TITLE
Changed search results to EXACT CONTAINS only

### PR DESCRIPTION
**Pull request by kthorat-prog**

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]

**Comment by oblodgett** [comment]
@kthorat-prog did you mean to include the empty file?

**Comment by kthorat-prog** [comment]
No....I deleted that one. Can you please recheck if its deleted and not commited.

**Comment by oblodgett** [comment]
Ok looks good

**Comment by kthorat-prog** [comment]
> Ok looks good

Thank you.

**Pull request merged**
