### PR TITLE
SCRUM-3708: fix validation for evidence

### PR DESCRIPTION
**Pull request by abecerra**

### CODE REVIEW

**Review by markquintontulloch — CHANGES_REQUESTED** [review]
Presumably you can remove the imports for ResourceDescriptorService and ResourceDescriptorPageService too?

**Comment by markquintontulloch** [comment]
Can you rename the test files so that the numbering is still sequential

**Comment by abecerra** [comment]
> Can you rename the test files so that the numbering is still sequential

Reordered

**Comment by abecerra** [comment]
> Presumably you can remove the imports for ResourceDescriptorService and ResourceDescriptorPageService too?

Removed

**Review by markquintontulloch — APPROVED** [review]

**Pull request merged**
