### PR TITLE
Fix for autocomplete fields SCRUM-1228

### PR DESCRIPTION
**Pull request by oblodgett**

### CODE REVIEW

**Comment by oblodgett** [comment]
@mluypaert wondering why these checks are being skipped?

**Comment by mluypaert** [comment]
> @mluypaert wondering why these checks are being skipped?

Updating the title triggered those skipped tests, but the first batch of tests ran and passed
image

**Comment by oblodgett** [comment]
Oh weird ok...

**Review by kthorat-prog — APPROVED** [review]

**Comment by mluypaert** [comment]
> Oh weird ok...

Ya, that's an unfortunate side-effect of enabling retriggering tests for PR that get their base branch changes (the only way is triggering on all updates and skip tests when the base branch wasn't changed)

**Pull request merged**
