### PR TITLE
SCRUM-2834 (update) Add new ontology fields to sort constants

### PR DESCRIPTION
**Pull request by markquintontulloch**

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]

**Comment by markquintontulloch** [comment]
@oblodgett - Let me know when is a good time to merge this (or go ahead and merge yourself) so that it doesn't kill any allele index testing

**Comment by oblodgett** [comment]
@mluypaert  is trying to do a backup right now then maybe we can merge this.

**Comment by mluypaert** [comment]
@markquintontulloch @oblodgett Alpha backup is done, so whenever you're ready for it.

**Comment by markquintontulloch** [comment]
@oblodgett Do you want to wait for allele indexing to finish?

**Comment by oblodgett** [comment]
No thats fine go ahead and deploy.

**Pull request merged**
