### PR TITLE
SCRUM-2970 Fix issue with header column

### PR DESCRIPTION
**Pull request by adamgibs**

### CODE REVIEW

**Comment by oblodgett** [comment]
@adamgibs sorry I think it needs to be `rc3`

**Comment by oblodgett** [comment]
19 rc3, considering 19 rc2 is on beta.

**Comment by adamgibs** [comment]
@oblodgett Shouldn't it be 20?

**Comment by mluypaert** [comment]
> @oblodgett Shouldn't it be 20?

@adamgibs Correct, though the branch for this PR should be `release/v0.20.0-rc3`, as `v0.20.0-rc2` is the version that's currently on beta (@markquintontulloch already applied a hotfix earlier, which he released as `v0.20.0-rc2`).

**Pull request closed without merging**
