### PR TITLE
Fix FB curie generation null pointer error

### PR DESCRIPTION
**Pull request by markquintontulloch**

### CODE REVIEW

**Review by oblodgett — APPROVED** [review]

**Comment by mluypaert** [comment]
Looks good to me, but may need to be cherry-picked onto `v0.16.0` and released as `v0.16.1` if @chris-grove would decide so.

**Review by mluypaert — APPROVED** [review]

**Comment by markquintontulloch** [comment]
> Looks good to me, but may need to be cherry-picked onto `v0.16.0` and released as `v0.16.1` if @chris-grove would decide so.

So hold off on merging? Or just merge anyway?

**Comment by mluypaert** [comment]
> > Looks good to me, but may need to be cherry-picked onto `v0.16.0` and released as `v0.16.1` if @chris-grove would decide so.
> 
> So hold off on merging? Or just merge anyway?

You can go ahead and merge anyway, as it's a single commit it can easily be cherry-picked to create a new commit onto v0.16.0 if needed.

**Comment by oblodgett** [comment]
@markquintontulloch should these have been caught with test files?

**Pull request merged**
