### PR TITLE
Release/v0.25.0

### PR DESCRIPTION
**Pull request by markquintontulloch**

### CODE REVIEW

**Comment by markquintontulloch** [comment]
@mluypaert I don't get it.  I've done the merge back from production but still getting conflicts on RELEASE-NOTES.md.  I can't resolve them via the command line as Github suggests because we can't push changes to release branches.

**Comment by mluypaert** [comment]
> @mluypaert I don't get it. I've done the merge back from production but still getting conflicts on RELEASE-NOTES.md. I can't resolve them via the command line as Github suggests because we can't push changes to release branches.

Normally you should be able to push changes directly to release branches. If not then I'll need to update a few branch protection rules.

**Comment by markquintontulloch** [comment]
`! [remote rejected]   release/v0.25.0 -> release/v0.25.0 (protected branch hook declined)`

**Comment by mluypaert** [comment]
> `! [remote rejected] release/v0.25.0 -> release/v0.25.0 (protected branch hook declined)`

@oblodgett Did you re-enable release branch protection rules? I though I deleted those earlier already 🤔 
@markquintontulloch Try again now, I've deleted the branch protection rule on the release branches that was blocking this.

**Review by mluypaert — APPROVED** [review]

**Pull request merged**
