### PR TITLE
PRmerge/beta

### PR DESCRIPTION
**Pull request by adamgibs**

### CODE REVIEW

**Comment by oblodgett** [comment]
@adamgibs I would guess that this PR should have changes?

**Comment by adamgibs** [comment]
@oblodgett No, it's just the change in utils that pushed into alpha yesterday for the column header stuff. So the change is already in alpha

**Comment by oblodgett** [comment]
I would guess that we don't need this PR then.

**Comment by adamgibs** [comment]
@oblodgett Per the README, "After prerelease creation and deployment, merge the beta branch back to alpha, to make the (pre)release tag reachable from alpha (and report the correct version number through git describe --tags)". Is that relevant here?

**Comment by oblodgett** [comment]
ya ok

**Review by oblodgett — APPROVED** [review]

**Pull request merged**
