### PR TITLE
Removed duplicate code PR into PR

### PR DESCRIPTION
**Pull request by oblodgett**
@markquintontulloch duplicate code has to be maintained twice so worked on getting that removed.

### CODE REVIEW

**Review by markquintontulloch — COMMENTED** [review]
I don't think this sets the record counts for the file correctly.  Won't it just give the count for the last load rather than the combined count?

**Comment by markquintontulloch** [comment]
Also, getting a duplicate primaryKey error when loading the 2nd ontology (XBS) using the refactored code
`ERROR: duplicate key value violates unique constraint "ontologyterm_pkey"
  Detail: Key (curie)=(XAO:0004284) already exists.`
  XAO:0004284 is a XBA term

**Comment by oblodgett** [comment]
Yes you are right on the term counts... here is a push to fix that

**Comment by oblodgett** [comment]
Does the first ontology need a specific config for its namespace? I would think XBA is loading all the terms?

**Comment by markquintontulloch** [comment]
XBA should just be loading those terms that match the default namespace

**Comment by oblodgett** [comment]
Ahh ok... might it be better to specify it?

config.getAltNameSpaces().add("xenopus_developmental_annatomy");
				processTerms(bulkLoadFile, OntologyBulkLoadType.XBA, xbaTermService, config);
				config.getAltNameSpaces().clear();
				config.getAltNameSpaces().add("xenopus_developmental_stage");
				processTerms(bulkLoadFile, OntologyBulkLoadType.XBS, xbsTermService, config);

**Review by markquintontulloch — APPROVED** [review]

**Pull request merged**
