### PR TITLE
SCRUM-3536 add LoadingOverlay to AlleleDetailPage

### PR DESCRIPTION
**Pull request by adamgibs**

### CODE REVIEW

**Review by abecerra — APPROVED** [review]

**Comment by oblodgett** [comment]
@adamgibs does this take over the whole page or only the portion under the allele symbol?

**Comment by adamgibs** [comment]
@oblodgett Whole page

**Comment by adamgibs** [comment]
Whole page under the main site header that is

**Review by oblodgett — APPROVED** [review]
I guess if the curator really want to do something else while an allele is saving they could just have another window to the site open.

**Comment by adamgibs** [comment]
Side bar is still functional. Just the page including the sticky header

**Pull request merged**
